### ISSUE TITLE
上传视频文件

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#10]
在群内上传视频文件  获取到的上传视频之后的文件 还需要解析一下吗？ 例如getImage 这样的方法 上传类型是否为103？

**Comment by ericliang** [comment]
你好，获取视频相关的URL有两个，一个是封面，一个是视频内容。均可参照Web版：

封面： https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/content/roster/renderMsg.vue#L168
视频内容就是附件URL： https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/content/roster/renderMsg.vue#L286

**Comment by ericliang** [comment]
关于上传类型。以Demo里有图片和文件为例，可参照 https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/content/roster/inputer.vue#L46

如果是视频，fileType为`video`，所有类型如下：
`const fileTypes = ['file', 'audio', 'image', 'video', 'shareFile', 'shareAudio', 'shareImage', 'shareVideo'];`

**Comment by floki2020** [comment]
> https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/content/roster/renderMsg.vue#L168

好的，感谢耐心指导！先做下测试！

**Comment by floki2020** [comment]
> 你好，获取视频相关的URL有两个，一个是封面，一个是视频内容。均可参照Web版：
> 
> 封面： https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/content/roster/renderMsg.vue#L168
> 视频内容就是附件URL： https://github.com/maxim-top/maxim-web/blob/master/src/ui/chatting/content/roster/renderMsg.vue#L286

您好！这个上传视频之后返回的只有url 没有tUrl  没有封面的地址！

**Comment by ericliang** [comment]
关于视频封面显示可参照最新Demo示例 https://github.com/maxim-top/maxim-uniapp/blob/master/pages/roster/message/index.vue#L106
