### ISSUE TITLE
好友聊天报错

### ISSUE THREAD

**Issue by spencer17x** [maxim-top/lanying-im-uniapp#11]
复现步骤：HBuilderX打开项目并运行到微信开发者工具=>登录=>好友=>点击好友进行聊天=>发送聊天内容
报错如下：

![image](https://user-images.githubusercontent.com/32794413/131302496-ba845647-f235-4728-b876-ea87c613520e.png)

**Comment by ericliang** [comment]
这个应该是在没有获取用户信息的情况返回的空 RosterInfo 导致，可以临时增加一个判断解决这个问题 https://github.com/maxim-top/maxim-uniapp/commit/2fcb8b731b102eec57fa8690c07cefc328b66533

库已更新，后续应该不需要在外层防御了 https://github.com/maxim-top/floo-uniapp/commit/17dda77653f71cf34a7d6a0eb8d73735034cd266
