### ISSUE TITLE
撤回消息，对方收不到消息ID

### ISSUE THREAD

**Issue by cdyxc** [maxim-top/lanying-im-uniapp#15]

**Comment by theorix** [comment]
这个就是要撤回的消息mid, 是个Long类型的对象。 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L159

**Comment by cdyxc** [comment]
这个是对方收到的完整消息， {"uid":"6661893837856","mid":{"low":-1145044971,"high":216111882,"unsigned":true}}  

没有消息ID我怎么把对应的那条消息删除呢、

**Comment by theorix** [comment]
"mid":{"low":-1145044971,"high":216111882,"unsigned":true}
上面这个就是消息ID，可以用这里的toNumber函数转成数字 https://github.com/maxim-top/maxim-uniapp/blob/84177fe696573a21eae67e58d00f265e24bc8318/third/tools.js#L62
