### ISSUE TITLE
如何屏蔽 SDK 输出的 log

### ISSUE THREAD

**Issue by ziiip** [maxim-top/lanying-im-uniapp#17]
现在 SDK 中输出的 log 非常多，影响其它功能的调试，是否能做一个开关，控制 log 的输出

**Comment by theorix** [comment]
可以加开关，我们先开发下

**Comment by ziiip** [comment]
> 

那就等你们的好消息了。

**Comment by theorix** [comment]
使用最新的sdk，然后初始化时设置logLevel为off就不输出sdk日志了
      const logLevel = 'off'; // debug|info|warn|error|off
      const config = {
        autoLogin,
        dnsServer,
        appid,
        ws,
        logLevel
      };
      const im = flooim(config);

**Comment by ziiip** [comment]
> 使用最新的sdk，然后初始化时设置logLevel为off就不输出sdk日志了
>   const logLevel = 'off'; // debug|info|warn|error|off
>   const config = {
>     autoLogin,
>     dnsServer,
>     appid,
>     ws,
>     logLevel
>   };
>   const im = flooim(config);

非常感谢你们快速响应。
