### ISSUE TITLE
用户退出群组，群内用户没有及时收到群组成员变化的通知

### ISSUE THREAD

**Issue by ziiip** [maxim-top/lanying-im-uniapp#18]
SDK： 蓝莺IM SDK Uniapp 版 v2.9.13

两个用户，加入同时加入同一个群聊，聊天没有遇到问题，但是，一个用户退出群聊 `.groupManage.asyncLeave(groupId)`， 另一个用户一直没有收到 `onGroupMemberChanged`。 然而，当退出的用户重新加入，会连续收到两个 `onGroupMemberChanged`，在收到的时候，立即查询群组成员，两次都是返回同样的数据，都包含着重新加入的用户。
这里会产生了问题：1. 用户感知不到其他用户的退出，2. SDK 通知群成员变化，但是找不出变化的地方。

这个问题产生于那里？SDK 还是服务端？

**Comment by ericliang** [comment]
这个问题有一种可能，是第一个 `onGroupMemberChanged` 事件延迟收到了。

假设用户A退出群聊再加入，用户B如果当时没有登录或者长链接断开，那么会在用户B登录成功的下一刻收到群成员变化通知，这时候刷新看起来是没变，实际上取到的是最新的列表。

可以在测试的时候，确认用户B的登录状态正常，如果正常还是出现问题，可以再等 30s 观察下。

**Comment by ziiip** [comment]
按照提示，我观察了一下。用户A退出后，等了三分钟，B 用户也没有收到 `onGroupMemberChanged` 事件。期间 B 用户可以正常发送消息。过了三分钟，A 用户重新进入，可以看到 B 用户在三分钟内所发送的消息。感觉这个  `onGroupMemberChanged` 事件在 A 退出后，没有被发出来？

**Comment by theorix** [comment]
是SDK的问题，明天会修复。

**Comment by ziiip** [comment]
👍

**Comment by ziiip** [comment]
@theorix 顺手反馈一个遇到问题，如果需要我这边也可以新开一个 issue。
如果没理解错，SDK 中应该有个 `toNumber` 的方法，这个方法有时候会报错，传进来的参数是 `null`，不知道是哪里的问题。同理的应该有 to 什么的可能也会有机会遇到这样的问题？

**Comment by theorix** [comment]
toNumber是转换用户或群ID时调用的，可以看下sdk日志里报错之前收到的消息, 是否用户或群ID是null

**Comment by theorix** [comment]
@ziiip 现在可以收到onGroupMemberChanged了 你使用最新的sdk试下

**Comment by ziiip** [comment]
@theorix  感谢快速响应。我尝试一下，遇到了问题

```
2023-01-16 12:41:20.479 [error] stringify error: TypeError: this.isZero is not a function
    at Object.O.toString (floo-2.0.0.uniapp.js:687)
    at a (floo-2.0.0.uniapp.js:4680)
    at v.toObject (floo-2.0.0.uniapp.js:4830)
    at Object.o.toJSON (floo-2.0.0.uniapp.js:2941)
    at JSON.stringify (<anonymous>)
    at j (floo-2.0.0.uniapp.js:6898)
    at Object.saveNotice (floo-2.0.0.uniapp.js:7414)
    at floo-2.0.0.uniapp.js:9392
    at floo-2.0.0.uniapp.js:7074
    at Array.forEach (<anonymous>) 6606084419600_key_notice_store [{…}](env: macOS,mp,1.06.2301040; lib: 2.29.1)
```

**Comment by theorix** [comment]
@ziiip this.isZero is not a function这个报错修复了，使用最新sdk试下

**Comment by ericliang** [comment]
@ziiip SDK已经开源，如果感兴趣，也欢迎随时建议👏🏻😁

本 issue 相关修改细节都能看到 https://github.com/maxim-top/floo-uniapp/commit/b1e578731f89768519502003153c0c2736e63074 https://github.com/maxim-top/floo-uniapp/commit/da71629af9aaf87e8d7ff6dbaa53cc8300fe2c00

**Comment by ziiip** [comment]
新年好啊

@theorix 可以了。
