### ISSUE TITLE
SDK storeBase.js  中，关于保存，获取和删除的判断逻辑有出入

### ISSUE THREAD

**Issue by ziiip** [maxim-top/lanying-im-uniapp#19]
[storeBase.js](https://github.dev/maxim-top/floo-uniapp/blob/c0c6f0c308d307a2bc0f7c5260bfd153c2dde62c/sdk/utils/store/storeBase.js#L27)

关于 `partition_key` 判读逻辑，不一致。
生成时，如果发送者 ID 为 0，会产生 `XXXX_key_roster_message_store` key，但是删除的时候，无法对其进行删除。

```javascript
const saveItem = (key, item, hasuid = true, partition_key = 0) => {

  ...

  if (partition_key > 0) {
    skey = skey + '_' + partitionId(partition_key);
  }

  ...

};

const getItem = (key, hasuid = true, partition_key = 0) => {

  ...

  if (partition_key > 0) {
    skey = skey + '_' + partitionId(partition_key);
  }

  ...

};

const removeItem = (key, hasuid = true, partition_key = -1) => {

  ...

  if (partition_key >= 0) {
    skey = skey + '_' + partitionId(partition_key);
  }

  ...

};
```

**Comment by theorix** [comment]
非常感谢你的反馈，之后会改成下面这样
```
const saveItem = (key, item, hasuid = true, partition_key = -1) => {

  ...

  if (partition_key >= 0) {
    skey = skey + '_' + partitionId(partition_key);
  }

  ...

};

const getItem = (key, hasuid = true, partition_key = -1) => {

  ...

  if (partition_key >= 0) {
    skey = skey + '_' + partitionId(partition_key);
  }

  ...

};
```

**Comment by theorix** [comment]
可以先用这个sdk测试 https://github.com/maxim-top/floo-uniapp/releases/download/v2.9.16/floo-2.0.0.uniapp.js

**Comment by ziiip** [comment]
> 可以先用这个sdk测试 https://github.com/maxim-top/floo-uniapp/releases/download/v2.9.16/floo-2.0.0.uniapp.js

这个版本可以清除新创建的了。旧的无法清除，因为不在条件里。


另外，发觉有一个 key 创建了，remove all 的时候也没有清除，但是没有什么大的影响，如下图。

<img width="405" alt="image" src="https://user-images.githubusercontent.com/8551909/224002183-98c1308c-f089-4154-b1bb-fb89773f77c0.png">

**Comment by theorix** [comment]
想删旧的数据可以在删除partition_key=0时，额外执行下removeItem(key, hasuid , -1)
这个没清除的key可能是：
1. sdk修改之前的partition_key=0时写的数据（这种情况应该主动删除后，使用新的sdk就不会发生了）
2. 其他用户的数据（这种情况removeAll只会删除当前用户的数据，不会删除其他用户的）

**Comment by ziiip** [comment]
使用了新的 SDK ，还是会出现，不过内容变了。我退出登录，剩下这几项。 `XXX_key_group_message_store` 不会被删除
<img width="529" alt="image" src="https://user-images.githubusercontent.com/8551909/224239658-521c8d1d-0c7a-4c50-b04b-c8f2e449408b.png">

**Comment by theorix** [comment]
第1个和第3个是忘记删了，第2个我这无法复现。 可以等下更新下 把这3种都删了。

**Comment by ziiip** [comment]
thanks

**Comment by theorix** [comment]
更新了
