### ISSUE TITLE
移动4G网络访问延迟严重

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#3]
![image](https://user-images.githubusercontent.com/1941819/91927286-ac569500-ed0b-11ea-8de9-11daf84d9787.png)
用WIFI 就没有问题
用移动4G网络要20秒才能登陆

**Comment by theorix** [comment]
试下这个地址登录 看看有问题没  https://chat2-h5.maximtop.com/

**Comment by ericliang** [comment]
可以同时登陆当前版本对比确认 https://chat.maximtop.com/

**Comment by ericliang** [comment]
> 我们在别的地方也是 访问慢 切换到WIFI 联通的 就没有问题

你们在哪？ 

@theorix 可以一起去找阿里云反馈一下，看看有没有更多信息

**Comment by floki2020** [comment]
我们在东北 客户在上海 电信说是也不行

**Comment by floki2020** [comment]
https://chat2-h5.maximtop.com/ 很慢
https://chat.maximtop.com/  很快

**Comment by ericliang** [comment]
> https://chat2-h5.maximtop.com/ 很慢
> https://chat.maximtop.com/ 很快

感谢，我刚才说的地址有问题，请再测试下 https://chat-h5.maximtop.com/

速度不要看页面刷新速度，要看点击登录后速度。

**Comment by floki2020** [comment]
不能注册 提示注册失败

**Comment by ericliang** [comment]
> 不能注册 提示注册失败

哪个地址？什么错误？三个链接都一样吗？

**Comment by floki2020** [comment]
用我们自己的账号登陆（已经切换appid） 显示的是token undefined

**Comment by floki2020** [comment]
> > 不能注册 提示注册失败
> 
> 哪个地址？什么错误？三个链接都一样吗？

三个网址都不行

**Comment by ericliang** [comment]
> > > 不能注册 提示注册失败
> > 
> > 
> > 哪个地址？什么错误？三个链接都一样吗？
> 
> 三个网址都不行

请提供下各端详细的日志，谢谢。

**Comment by floki2020** [comment]
> > > > 不能注册 提示注册失败
> > > 
> > > 
> > > 哪个地址？什么错误？三个链接都一样吗？
> > 
> > 
> > 三个网址都不行
> 
> 请提供下各端详细的日志以及账号，谢谢。

没用测试手机 没有日志
账号都注册不了咋弄
不能登陆的账号 fei_123

**Comment by theorix** [comment]
是阿里云SLB网络有问题, 已反馈给阿里云了

**Comment by floki2020** [comment]
谢谢

**Comment by floki2020** [comment]
> 是阿里云SLB网络有问题, 已反馈给阿里云了

反馈之后有结果了吗？

**Comment by theorix** [comment]
还没有。
这边先优化了下：
1. 修改了重连策略，在网络不稳定情况下延迟超时时间；
2. 去掉了onHide() 里面的对监听器的错误移除；
你可以用http://chat-h5.maximtop.com/  试下有没有效果，如果有的话，可以按照 maxim-uniapp 里的更新修改下自己的程序。

**Comment by floki2020** [comment]
> 还没有。
> 这边先优化了下：
> 
> 1. 修改了重连策略，在网络不稳定情况下延迟超时时间；
> 2. 去掉了onHide() 里面的对监听器的错误移除；
>    你可以用http://chat-h5.maximtop.com/  试下有没有效果，如果有的话，可以按照 maxim-uniapp 里的更新修改下自己的程序。

明白

**Comment by floki2020** [comment]
> > 还没有。
> > 这边先优化了下：
> > 
> > 1. 修改了重连策略，在网络不稳定情况下延迟超时时间；
> > 2. 去掉了onHide() 里面的对监听器的错误移除；
> >    你可以用http://chat-h5.maximtop.com/  试下有没有效果，如果有的话，可以按照 maxim-uniapp 里的更新修改下自己的程序。
> 
> 明白

现在这个还是登陆不了啊 也注册不了啊  就是用这个网址 然后用的4G 注册也不能注册 切换成我们自己的appid 也不能登陆 麻烦你那边也用手机测试下！

**Comment by theorix** [comment]
用这个地址试试呢 https://chat2-h5.maximtop.com/ ， 也许是刷新有问题，换个浏览器试试呢，比如chrome。 (我这边网络一直是正常的。。）

**Comment by floki2020** [comment]
> 用这个地址试试呢 https://chat2-h5.maximtop.com/ ， 也许是刷新有问题，换个浏览器试试呢，比如chrome。 (我这边网络一直是正常的。。）

你用的是移动4G网络吗？

**Comment by theorix** [comment]
不是 只有联通的4G

**Comment by floki2020** [comment]
> 不是 只有联通的4G

需要更新sdk吧？ 我没有在onHide中监听 没有操作 那我更新下SDK 然后编一个app 看看情况

**Comment by floki2020** [comment]
![image](https://user-images.githubusercontent.com/1941819/92071962-b3040b80-ede2-11ea-8022-3648b5d5b650.png)
更新了sdk 之后的效果 H5登陆没有问题  WIFI下登陆也没有问题  只有在 4G网络情况下出现这样的问题 不能登陆

**Comment by floki2020** [comment]
切换WIFI 瞬间就能登陆

**Comment by ericliang** [comment]
听起来跟 App 实现关系很大，还请务必确认系统中没有其他 removeListener 的操作，类似 https://github.com/maxim-top/maxim-uniapp/commit/f061a57079d96abacbfaf4f9fff45ea743fc4d59

还有一种可能，是跟网络过慢有关系，我们重新延长了超时的设置，也请更新一下测试，详情见 https://github.com/maxim-top/maxim-uniapp/commit/33dfd5309a16723433001aa810386212e3b2aa78

**Comment by floki2020** [comment]
> 听起来跟 App 实现关系很大，还请务必确认系统中没有其他 removeListener 的操作，类似 [f061a57](https://github.com/maxim-top/maxim-uniapp/commit/f061a57079d96abacbfaf4f9fff45ea743fc4d59)
> 
> 还有一种可能，是跟网络过慢有关系，我们重新延长了超时的设置，也请更新一下测试，详情见 [33dfd53](https://github.com/maxim-top/maxim-uniapp/commit/33dfd5309a16723433001aa810386212e3b2aa78)

1.所有的removeListener 操作都要去掉吗？
2.更新 需要再更新下sdk吗？

**Comment by floki2020** [comment]
removeListener 还是removeIMListener？

**Comment by ericliang** [comment]
> > 听起来跟 App 实现关系很大，还请务必确认系统中没有其他 removeListener 的操作，类似 [f061a57](https://github.com/maxim-top/maxim-uniapp/commit/f061a57079d96abacbfaf4f9fff45ea743fc4d59)
> > 还有一种可能，是跟网络过慢有关系，我们重新延长了超时的设置，也请更新一下测试，详情见 [33dfd53](https://github.com/maxim-top/maxim-uniapp/commit/33dfd5309a16723433001aa810386212e3b2aa78)
> 
> 1.所有的removeListener 操作都要去掉吗？

除了页面 unLoad() 外，其他地方都不要有。是 removeIMListeners()。

> 2.更新 需要再更新下sdk吗？

需要。

**Comment by floki2020** [comment]
> > > 听起来跟 App 实现关系很大，还请务必确认系统中没有其他 removeListener 的操作，类似 [f061a57](https://github.com/maxim-top/maxim-uniapp/commit/f061a57079d96abacbfaf4f9fff45ea743fc4d59)
> > > 还有一种可能，是跟网络过慢有关系，我们重新延长了超时的设置，也请更新一下测试，详情见 [33dfd53](https://github.com/maxim-top/maxim-uniapp/commit/33dfd5309a16723433001aa810386212e3b2aa78)
> > 
> > 
> > 1.所有的removeListener 操作都要去掉吗？
> 
> 除了页面 unLoad() 外，其他地方都不要有。是 removeIMListeners()。
> 
> > 2.更新 需要再更新下sdk吗？
> 
> 需要。

1.整个工程只有在 Register 和Login 的onUnload 添加了removeIMListeners() 别的地方没有
2.更换了SDK 
 结果：到了 请求部分就不在继续走了
![image](https://user-images.githubusercontent.com/1941819/92082851-af2eb400-edf7-11ea-8e9a-3ce654a61da7.png)

输出的日志就这些

**Comment by ericliang** [comment]
建议检查下集成代码，这两个错误不是 SDK 的错误。

**Comment by floki2020** [comment]
> 建议检查下集成代码，这两个错误不是 SDK 的错误。

这个错误到不是重点，所有的集成的逻辑都是参照咱们官方的例子操作的！没有其他的东西

**Comment by ericliang** [comment]
Demo 应该没有改动的，你重启下 IDE 试试？

**Comment by floki2020** [comment]
> Demo 应该没有改动的，你重启下 IDE 试试？

重启了也没用 改过之后根本就进不去了  之前转半天还是能进去的 ！彻底搞不清楚怎么回事了

**Comment by floki2020** [comment]
能监控到 我向服务端请求 有没有结果吗？

**Comment by ericliang** [comment]
> > Demo 应该没有改动的，你重启下 IDE 试试？
> 
> 重启了也没用 改过之后根本就进不去了 之前转半天还是能进去的 ！彻底搞不清楚怎么回事了

回退 SDK 好用吗？

另外，看一下网络调用有没有异常。

**Comment by ericliang** [comment]
> 能监控到 我向服务端请求 有没有结果吗？

看情况猜测，这个请求发送都没有成功，本地看网络应该是能看出来的。

**Comment by floki2020** [comment]
请求的时候好像是没有网络 在登陆中添加了 检测网络变化状态的函数，结果是没有返回值的！
![image](https://user-images.githubusercontent.com/1941819/92096353-5c5df800-ee09-11ea-9754-81a1de2d9613.png)
![image](https://user-images.githubusercontent.com/1941819/92096382-64b63300-ee09-11ea-9e43-cc34f9867cbe.png)
本地网络 还看不到  uniapp app端测试的  用webview查看 也看不到啥信息！

**Comment by floki2020** [comment]
刚才直接用request 请求试了下 往咱们的服务器后台发就没有反应 往我们自己的服务器发送请求就有结果 而且都是4G的情况！

**Comment by ericliang** [comment]
> 刚才直接用request 请求试了下 往咱们的服务器后台发就没有反应 往我们自己的服务器发送请求就有结果 而且都是4G的情况！

请求的哪个地址？

**Comment by ericliang** [comment]
> 请求的时候好像是没有网络 在登陆中添加了 检测网络变化状态的函数，结果是没有返回值的！
> ![image](https://user-images.githubusercontent.com/1941819/92096353-5c5df800-ee09-11ea-9754-81a1de2d9613.png)
> ![image](https://user-images.githubusercontent.com/1941819/92096382-64b63300-ee09-11ea-9e43-cc34f9867cbe.png)
> 本地网络 还看不到 uniapp app端测试的 用webview查看 也看不到啥信息！

可以去社区问一下他们？我看之前也有人提过 https://github.com/dcloudio/uni-app/issues/1049

**Comment by floki2020** [comment]
> > 刚才直接用request 请求试了下 往咱们的服务器后台发就没有反应 往我们自己的服务器发送请求就有结果 而且都是4G的情况！
> 
> 请求的哪个地址？

token/login 请求的这个  检测状态的那个用处也不大  主要是访问我们自己的网址是直接有返回值的

**Comment by floki2020** [comment]
![image](https://user-images.githubusercontent.com/1941819/92100946-01c79a80-ee0f-11ea-9f15-4fa4dc41cf38.png)
![image](https://user-images.githubusercontent.com/1941819/92100975-0b510280-ee0f-11ea-8577-f45e8cbc0bf7.png)

切换4G的结果
![image](https://user-images.githubusercontent.com/1941819/92101220-62ef6e00-ee0f-11ea-8dae-e51fd8ca7ee4.png)

**Comment by floki2020** [comment]
新手小白 还望指导下

**Comment by ericliang** [comment]
> ![image](https://user-images.githubusercontent.com/1941819/92100946-01c79a80-ee0f-11ea-9f15-4fa4dc41cf38.png)
> ![image](https://user-images.githubusercontent.com/1941819/92100975-0b510280-ee0f-11ea-8577-f45e8cbc0bf7.png)
> 
> 切换4G的结果
> ![image](https://user-images.githubusercontent.com/1941819/92101220-62ef6e00-ee0f-11ea-8dae-e51fd8ca7ee4.png)

我看这个结果是成功的？

**Comment by floki2020** [comment]
这个我打错了  上面的是4G的 下面的是WiFi的 
4G是不能post
@ericliang

**Comment by floki2020** [comment]
能在咱们这边做下测试吗？发送一个app 测试一下！这个问题困扰好几天了

**Comment by ericliang** [comment]
> > > 刚才直接用request 请求试了下 往咱们的服务器后台发就没有反应 往我们自己的服务器发送请求就有结果 而且都是4G的情况！
> > 
> > 
> > 请求的哪个地址？
> 
> token/login 请求的这个 检测状态的那个用处也不大 主要是访问我们自己的网址是直接有返回值的

请问你们自己的请求是 HTTPS 吗？

**Comment by floki2020** [comment]
> > > > 刚才直接用request 请求试了下 往咱们的服务器后台发就没有反应 往我们自己的服务器发送请求就有结果 而且都是4G的情况！
> > > 
> > > 
> > > 请求的哪个地址？
> > 
> > 
> > token/login 请求的这个 检测状态的那个用处也不大 主要是访问我们自己的网址是直接有返回值的
> 
> 请问你们自己的请求是 HTTPS 吗？

我们用的是HTTP请求 没有用HTTPS

**Comment by floki2020** [comment]
你们能用4G网络 然后请求下服务吗？这边用这个操作都是请求超时
![image](https://user-images.githubusercontent.com/1941819/92211071-6ee83800-eec2-11ea-81ec-0202c22655df.png)

@ericliang

**Comment by ericliang** [comment]
> 你们能用4G网络 然后请求下服务吗？这边用这个操作都是请求超时
> ![image](https://user-images.githubusercontent.com/1941819/92211071-6ee83800-eec2-11ea-81ec-0202c22655df.png)
> 
> @ericliang

我们这边找了几台手机测试，联通和移动 4G 都没有复现。看起来这个问题还是跟地区性的网络原因有关。

**Comment by floki2020** [comment]
> > 你们能用4G网络 然后请求下服务吗？这边用这个操作都是请求超时
> > ![image](https://user-images.githubusercontent.com/1941819/92211071-6ee83800-eec2-11ea-81ec-0202c22655df.png)
> > @ericliang
> 
> 我们这边找了几台手机测试，联通和移动 4G 都没有复现。看起来这个问题还是跟地区性的网络原因有关。

能用我们的app 试试吗？http://d.firim.vip/yxlt 看看在你们那登陆有没有问题 我们的是iOS也没有问题 只有安卓的包有这个问题

**Comment by floki2020** [comment]
我用咱们的maxim-uniapp 打包了一个刚开始能登陆 就用我们的也打包了 结果发现还是不能登陆，以为是我们打包的问题，可切换到咱们这app 重新测试发现还是不能登陆！如此看来还是** 网络**的问题，昨天也出短时间能登陆的情况 ！今天能登陆的 时间大概在9：40分左右，可以查下服务器的日志！还有就是 机房位置在哪能否在增加个其他网络的机房试试！ 网络还应该是网络问题！
@ericliang @theorix

**Comment by floki2020** [comment]
也打扰大家好几天了，经过这些天的测试！总结出来一些结果！
打包成的android 无论是我们自己的 还是maxim-uniapp 的例子 都不好用！在4G的情况下（有时候会好用 仅限上午某个时间段）之后就都不好用了
我们自己的app 打包成iOS 4G下任何时间都没有问题！
具体原因就这些
发布过issue
[https://github.com/dcloudio/uni-app/issues/2096#issue-692641516](url)

**Comment by ericliang** [comment]
> https://github.com/dcloudio/uni-app/issues/2096#issue-692641516

好的，我们正在积极配合 Uniapp 那边，有进展会第一时间回复。

**Comment by ericliang** [comment]
> > > > > 刚才直接用request 请求试了下 往咱们的服务器后台发就没有反应 往我们自己的服务器发送请求就有结果 而且都是4G的情况！
> > > > 
> > > > 
> > > > 请求的哪个地址？
> > > 
> > > 
> > > token/login 请求的这个 检测状态的那个用处也不大 主要是访问我们自己的网址是直接有返回值的
> > 
> > 
> > 请问你们自己的请求是 HTTPS 吗？
> 
> 我们用的是HTTP请求 没有用HTTPS

这个测试，你们自己的域名能换成 HTTPS 测试下吗？

**Comment by floki2020** [comment]
刚才登陆是非常快 不知道是咋回事

**Comment by zmobs** [comment]
你好。 我是uniapp 的开发人员。 能不能留一下qq.  我们一起排查一下这个问题

**Comment by floki2020** [comment]
> 你好。 我是uniapp 的开发人员。 能不能留一下qq. 我们一起排查一下这个问题

286029586

**Comment by floki2020** [comment]
> 你好。 我是uniapp 的开发人员。 能不能留一下qq. 我们一起排查一下这个问题

添加了吗？要不然留下你的联系方式 我添加你！

**Comment by theorix** [comment]
ucloud那边查到s-1-3-api.maximtop.cn 有时会解析到ipv6的地址，可能是这个导致的，现在删掉了ipv6的解析， @floki2020  试下有效果吗

**Comment by floki2020** [comment]
> ucloud那边查到s-1-3-api.maximtop.cn 有时会解析到ipv6的地址，可能是这个导致的，现在删掉了ipv6的解析， @floki2020 试下有效果吗

叫客户去试了！这边测试还行 应该是有效果的

**Comment by floki2020** [comment]
> ucloud那边查到s-1-3-api.maximtop.cn 有时会解析到ipv6的地址，可能是这个导致的，现在删掉了ipv6的解析， @floki2020 试下有效果吗

客户的反馈就是比之前是强了最起码登陆这块是比之前快了些了 别的地方也还是慢 还没有彻底好

**Comment by ericliang** [comment]
> > ucloud那边查到s-1-3-api.maximtop.cn 有时会解析到ipv6的地址，可能是这个导致的，现在删掉了ipv6的解析， @floki2020 试下有效果吗
> 
> 客户的反馈就是比之前是强了最起码登陆这块是比之前快了些了 别的地方也还是慢 还没有彻底好

可以明确下有问题的地方吗？

**Comment by floki2020** [comment]
> > > ucloud那边查到s-1-3-api.maximtop.cn 有时会解析到ipv6的地址，可能是这个导致的，现在删掉了ipv6的解析， @floki2020 试下有效果吗
> > 
> > 
> > 客户的反馈就是比之前是强了最起码登陆这块是比之前快了些了 别的地方也还是慢 还没有彻底好
> 
> 可以明确下有问题的地方吗？

目前客户反馈的情况：有视频 我稍后发给艾姆姐
1.能获取未读消息数 但是 消息列表获取不到
2.和单人进行聊天 消息发出后 不显示
3.个人详情也获取不到信息

**Comment by theorix** [comment]
这个可以取到客户端的log吗

**Comment by floki2020** [comment]
> 这个可以取到客户端的log吗

![image](https://user-images.githubusercontent.com/1941819/92694145-355b7500-f379-11ea-888a-c4491d036272.png)
这个错误是怎么回事呢？是我们客户端处理的时候有问题吗？

**Comment by floki2020** [comment]
> 这个可以取到客户端的log吗

稍后看看

**Comment by ericliang** [comment]
> > 这个可以取到客户端的log吗
> 
> ![image](https://user-images.githubusercontent.com/1941819/92694145-355b7500-f379-11ea-888a-c4491d036272.png)
> 这个错误是怎么回事呢？是我们客户端处理的时候有问题吗？

这个错误印象中你们反馈过，是在 JSON 里放中文字符的问题，当时去掉了。

**Comment by floki2020** [comment]
> > > 这个可以取到客户端的log吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/1941819/92694145-355b7500-f379-11ea-888a-c4491d036272.png)
> > 这个错误是怎么回事呢？是我们客户端处理的时候有问题吗？
> 
> 这个错误印象中你们反馈过，是在 JSON 里放中文字符的问题，当时去掉了。

对  我们这边传递过去的json 应该是没有问题的呀！ 但是 在获取list的时候 解析就错了！
![image](https://user-images.githubusercontent.com/1941819/92697324-c2083200-f37d-11ea-8b83-a01a721b469b.png)

**Comment by floki2020** [comment]
content里面的中文 和聊天里面的中文不都是一回事吗？ 怎么解析失败了呢 @ericliang

**Comment by ericliang** [comment]
> > > > 这个可以取到客户端的log吗
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/1941819/92694145-355b7500-f379-11ea-888a-c4491d036272.png)
> > > 这个错误是怎么回事呢？是我们客户端处理的时候有问题吗？
> > 
> > 
> > 这个错误印象中你们反馈过，是在 JSON 里放中文字符的问题，当时去掉了。
> 
> 对 我们这边传递过去的json 应该是没有问题的呀！ 但是 在获取list的时候 解析就错了！
> ![image](https://user-images.githubusercontent.com/1941819/92697324-c2083200-f37d-11ea-8b83-a01a721b469b.png)

list.vue 是你们自己的代码吧？看看是什么内容？

**Comment by floki2020** [comment]
list.vue 没什么东西 就是 遍历 了一下 getConversationList 没有别的东西了！ 我知道客户说的卡 不能发表情的问题 就是这个出错了导致的 我现在也是 报错 不能获取getConversationList 麻烦您看下 您那边的JSON.pase 有没有问题 我这边传递过去的 content 你也看到了！日志里有！麻烦看看

**Comment by floki2020** [comment]
![image](https://user-images.githubusercontent.com/1941819/92703709-01864c80-f385-11ea-9f49-3984db34b9ec.png)
@ericliang  貌似找到问题了  这里应该是个json格式 但是传递过去的不是 
sendMentionMessage 里面的参数 txt 是string 还是json？

**Comment by ericliang** [comment]
> ![image](https://user-images.githubusercontent.com/1941819/92703709-01864c80-f385-11ea-9f49-3984db34b9ec.png)
> @ericliang 貌似找到问题了 这里应该是个json格式 但是传递过去的不是
> sendMentionMessage 里面的参数 txt 是string 还是json？

Content 默认都是按照 String 处理的。

**Comment by floki2020** [comment]
> > ![image](https://user-images.githubusercontent.com/1941819/92703709-01864c80-f385-11ea-9f49-3984db34b9ec.png)
> > @ericliang 貌似找到问题了 这里应该是个json格式 但是传递过去的不是
> > sendMentionMessage 里面的参数 txt 是string 还是json？
> 
> Content 默认都是按照 String 处理的。

新建了一个号就发了一条信息 只有这里的是content 是string 才报错！ 您那边确认下 是否是 强制转JSON了 因为这个是Mention 是要写进消息里面的  可能是json 格式的！我需要你那边确认下

**Comment by ericliang** [comment]
> > > ![image](https://user-images.githubusercontent.com/1941819/92703709-01864c80-f385-11ea-9f49-3984db34b9ec.png)
> > > @ericliang 貌似找到问题了 这里应该是个json格式 但是传递过去的不是
> > > sendMentionMessage 里面的参数 txt 是string 还是json？
> > 
> > 
> > Content 默认都是按照 String 处理的。
> 
> 新建了一个号就发了一条信息 只有这里的是content 是string 才报错！ 您那边确认下 是否是 强制转JSON了 因为这个是Mention 是要写进消息里面的 可能是json 格式的！我需要你那边确认下

确认，你用 Demo 对比一下就知道。如果你自己的消息可能是 JSON 或 String，建议自己加一下转化处理。

**Comment by floki2020** [comment]
> > > > ![image](https://user-images.githubusercontent.com/1941819/92703709-01864c80-f385-11ea-9f49-3984db34b9ec.png)
> > > > @ericliang 貌似找到问题了 这里应该是个json格式 但是传递过去的不是
> > > > sendMentionMessage 里面的参数 txt 是string 还是json？
> > > 
> > > 
> > > Content 默认都是按照 String 处理的。
> > 
> > 
> > 新建了一个号就发了一条信息 只有这里的是content 是string 才报错！ 您那边确认下 是否是 强制转JSON了 因为这个是Mention 是要写进消息里面的 可能是json 格式的！我需要你那边确认下
> 
> 确认，你用 Demo 对比一下就知道。如果你自己的消息可能是 JSON 或 String，建议自己加一下转化处理。

收到  我去看了下web的demo  uniapp  没有这个 麻烦看下我的另一个问题！速度可以了 4G移动的问题ok了！

**Comment by ericliang** [comment]
问题已解决，关闭。感谢 @zmobs 给力支持，赞 Uniapp !
