### ISSUE TITLE
登陆后需要退出一下app 才能登陆

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#4]
当在操作一会app的时候 提示要求登陆  登陆之后填写账号密码后 再登陆 就一直显示登陆中  需要退出（切出去再切换回来）才能登陆
![image](https://user-images.githubusercontent.com/1941819/92699761-93d82180-f380-11ea-8790-3fc43e189509.png)

**Comment by floki2020** [comment]
个人觉得 这个判断有问题！ 只有当socket断开之后 他才重连 要不然 就提示让登陆！麻烦看一下

**Comment by ericliang** [comment]
> 个人觉得 这个判断有问题！ 只有当socket断开之后 他才重连 要不然 就提示让登陆！麻烦看一下

抱歉，这句话没太看明白，你是说希望重连不提示重登陆吗？

**Comment by floki2020** [comment]
> > 个人觉得 这个判断有问题！ 只有当socket断开之后 他才重连 要不然 就提示让登陆！麻烦看一下
> 
> 抱歉，这句话没太看明白，你是说希望重连不提示重登陆吗？

就是在测试中 和用户测试 遇到很多次！ 感觉是这么个状态，用户还在app中 某一个页面  可以在这个页面正常操作！当退出这个页面的时候 就跳转到登陆页面了！然后登陆操作！ 就开始转圈 （因为还应该是保持登陆的状态，所以转圈显示登陆中） 切换出去后 onHide 之后 再回去  reconnect socket  正常登陆！

**Comment by floki2020** [comment]
这个问题是这样的  就是客户小退 或者切换到别的应用了 再回来 就显示 要求其重新登陆！

**Comment by floki2020** [comment]
没有人了啊 ？

**Comment by ericliang** [comment]
你好，经过我们排查，这个问题可能与以下两个问题有关：

1. Demo里关于 relogin 通知的处理比较粗暴，有些情况下其实不需要通知，比如 Token 失效的情况下可以自动获取重新登录；
2. Uniapp的 websocket 链接有数量限制，会导致有些情况下 socket 链接失败，我们在错误处理地方增加了回收机制；

以上，已发布在 v2.7.2 版本 https://github.com/maxim-top/maxim-uniapp/commit/7230d881785aa0366a3ca5dc7051a3f63687e2fc ，请更新后测试，谢谢。

**Comment by floki2020** [comment]
> 你好，经过我们排查，这个问题可能与以下两个问题有关：
> 
> 1. Demo里关于 relogin 通知的处理比较粗暴，有些情况下其实不需要通知，比如 Token 失效的情况下可以自动获取重新登录；
> 2. Uniapp的 websocket 链接有数量限制，会导致有些情况下 socket 链接失败，我们在错误处理地方增加了回收机制；
> 
> 以上，已发布在 v2.7.2 版本 [7230d88](https://github.com/maxim-top/maxim-uniapp/commit/7230d881785aa0366a3ca5dc7051a3f63687e2fc) ，请更新后测试，谢谢。

好的  这里面主要就是检测链接状态这里！我马上更新测试下

**Comment by floki2020** [comment]
在测试的时候 比如说 有修改 需要重启运行下 HBuilder  log显示还没有断开 而界面就出现让登陆了  然后输入用户名密码 进行登陆就转圈了 必须退一下才行

**Comment by ericliang** [comment]
> 在测试的时候 比如说 有修改 需要重启运行下 HBuilder log显示还没有断开 而界面就出现让登陆了 然后输入用户名密码 进行登陆就转圈了 必须退一下才行

前面部分应该属于 HBuilder 的正常反应。后面再次重新输入用户名密码转圈的情况前面已经说明，原来是通过 relogin 触发的重新登录，其实不需要，应该去掉。

**Comment by ericliang** [comment]
根据反馈问题已解决，关闭此issue，如有问题可再次打开。
