### ISSUE TITLE
删除会话报错

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#5]
![image](https://user-images.githubusercontent.com/1941819/93036380-4c98ac00-f672-11ea-89b1-3a8ace4f0cab.png)

有时候好使 有时候出错
getApp().getIM().sysManage.deleteConversation(i.sid,true);

**Comment by ericliang** [comment]
> sysManage.deleteConversation



> ![image](https://user-images.githubusercontent.com/1941819/93036380-4c98ac00-f672-11ea-89b1-3a8ace4f0cab.png)
> 
> 有时候好使 有时候出错
> getApp().getIM().sysManage.deleteConversation(i.sid,true);

你好，感谢反馈，这个错误一般出现重复删除的时候。已经增加删除前的存在性检查，将会在本周内发布。

**Comment by ericliang** [comment]
v2.7.2 https://github.com/maxim-top/maxim-uniapp/commit/7230d881785aa0366a3ca5dc7051a3f63687e2fc 已发布，还请确认，谢谢。

**Comment by floki2020** [comment]
> v2.7.2 [7230d88](https://github.com/maxim-top/maxim-uniapp/commit/7230d881785aa0366a3ca5dc7051a3f63687e2fc) 已发布，还请确认，谢谢。

好的 更新下 试试

**Comment by floki2020** [comment]
你这是又更新的了吗？

**Comment by ericliang** [comment]
> 你这是又更新的了吗？

已在其他渠道确认，如果没有问题，此问题将会关闭。如有需要可重新打开。
