### ISSUE TITLE
更新完SDK  检测不过去 一直登陆不上 重新刷新才可以登录

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#6]
更新最新版本的SDK  并且按照最新的修改方案修改了下登陆里面的sdk初始化的检查
但是 检查始终不能过去，退出重新进 才能通过！

**Comment by ericliang** [comment]
你好，这里有两个信息可能对你有用：
1. isReady 只是返回了内部一个Flag，所以肯定不会阻塞调用；
2. 你这种情况可能是SDK初始化未完成就进行检查，所以检查不通过，但也没有重试。

建议检查下使用方式，可以参考 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L48

**Comment by floki2020** [comment]
> 你好，这里有两个信息可能对你有用：
> 
> 1. isReady 只是返回了内部一个Flag，所以肯定不会阻塞调用；
> 2. 你这种情况可能是SDK初始化未完成就进行检查，所以检查不通过，但也没有重试。
> 
> 建议检查下使用方式，可以参考 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L48

明天再试一下 这个地方 我按照你们的修改进行 等待了 但是就是过不去！

**Comment by ericliang** [comment]
> > 你好，这里有两个信息可能对你有用：
> > 
> > 1. isReady 只是返回了内部一个Flag，所以肯定不会阻塞调用；
> > 2. 你这种情况可能是SDK初始化未完成就进行检查，所以检查不通过，但也没有重试。
> > 
> > 建议检查下使用方式，可以参考 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L48
> 
> 明天再试一下 这个地方 我按照你们的修改进行 等待了 但是就是过不去！

好的，如果仍然不行，也请贴一下日志。

**Comment by floki2020** [comment]
> > > 你好，这里有两个信息可能对你有用：
> > > 
> > > 1. isReady 只是返回了内部一个Flag，所以肯定不会阻塞调用；
> > > 2. 你这种情况可能是SDK初始化未完成就进行检查，所以检查不通过，但也没有重试。
> > > 
> > > 建议检查下使用方式，可以参考 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L48
> > 
> > 
> > 明天再试一下 这个地方 我按照你们的修改进行 等待了 但是就是过不去！
> 
> 好的，如果仍然不行，也请贴一下日志。

![image](https://user-images.githubusercontent.com/1941819/98771486-89d5ac00-241f-11eb-9c62-033437ba528e.png)

**Comment by floki2020** [comment]
搞不明白了  登录一直有问题  登录是按照咱们的uniapp demo写的！ 退出登录再重新登录就不行！ 就是一直转圈登录中 也没有任何的请求

**Comment by floki2020** [comment]
13:14:40.969 SEND :{"vsn":0,"compress_method":0,"command":0}
13:14:41.012 RECV :{"payload":{"unread":[],"status":{"code":1}}}

**Comment by floki2020** [comment]
退出客户端 重新进 就能登陆了

**Comment by floki2020** [comment]
![image](https://user-images.githubusercontent.com/1941819/98776432-de7e2480-2429-11eb-8930-061b1b015961.png)
就是在这个 socket reconnect due to 这里 切换出去之后再回来 才有请求

**Comment by ericliang** [comment]
这个问题应该是 Demo 示例代码Bug，已经更新，请参考测试 https://github.com/maxim-top/maxim-uniapp/commit/a8d51546f9d4b9973466cc36abffb3c5c08c07b6

**Comment by floki2020** [comment]
> 这个问题应该是 Demo 示例代码Bug，已经更新，请参考测试 [a8d5154](https://github.com/maxim-top/maxim-uniapp/commit/a8d51546f9d4b9973466cc36abffb3c5c08c07b6)

谢谢 这个是好了！
