### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#8]
im.sysManage.getImage 解析的图片地址 访问是
![image](https://user-images.githubusercontent.com/1941819/99137193-fa6d0a80-2663-11eb-8f3f-48702ab517f7.png)

**Comment by ericliang** [comment]
> im.sysManage.getImage 解析的图片地址 访问是
> ![image](https://user-images.githubusercontent.com/1941819/99137193-fa6d0a80-2663-11eb-8f3f-48702ab517f7.png)

你好，这个错误是客户端参数错误，请仔细检查使用方式。

PS：如果地址无法访问，Demo上不可能显示头像的。

**Comment by floki2020** [comment]
同一个页面 同样一个方法  for循环里面的图片就不显示   
![image](https://user-images.githubusercontent.com/1941819/99139812-f696b380-2676-11eb-8b37-ed4c1ae3d5a4.png)

**Comment by floki2020** [comment]
可能跟你这个没有关系吧  但是这个地址是解析不出来！						
```
item.avatar = im.sysManage.getImage({
								avatar: item.avatar,
								type:'roster', 
								thumbnail:true,
								sdefault: '/static/img/avatar.jpg'
							})
```

**Comment by ericliang** [comment]
> 同一个页面 同样一个方法 for循环里面的图片就不显示
> ![image](https://user-images.githubusercontent.com/1941819/99139812-f696b380-2676-11eb-8b37-ed4c1ae3d5a4.png)

不是 for 循环就可以吗？可以看看代码，比较循环内外的区别。

另外，可观察下请求返回，是否有触发限流 429 错误？

**Comment by ericliang** [comment]
客户超一月无反馈，关闭此问题，如有更新可再次打开。
