### ISSUE TITLE
登录出错问题

### ISSUE THREAD

**Issue by floki2020** [maxim-top/lanying-im-uniapp#9]
现在是如果是做登陆操作输错了密码 就会 好几个错误提示 并且还能弹出 让手动录入等信息

**Comment by ericliang** [comment]
> 现在是如果是做登陆操作输错了密码 就会 好几个错误提示 并且还能弹出 让手动录入等信息

你好，没明白你的问题？

**Comment by floki2020** [comment]
登陆输入错误的密码 就会出现一连串的提示  并且 还自动登陆！

**Comment by ericliang** [comment]
你好，如果我没理解错的话，在登陆失败的情况下，Demo会尝试自动登录，之前没有重试限制，所以会持续提醒。Demo示例代码如下，可参照修改 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L160

上层应用在实现时要注意自动登录和手工登录的区别，并分别处理。

**Comment by floki2020** [comment]
> 你好，如果我没理解错的话，在登陆失败的情况下，Demo会尝试自动登录，之前没有重试限制，所以会持续提醒。Demo示例代码如下，可参照修改 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L160
> 
> 上层应用在实现时要注意自动登录和手工登录的区别，并分别处理。

忘记回复了！这个修改就是按照 这个链接里面的修改的！

**Comment by ericliang** [comment]
> > 你好，如果我没理解错的话，在登陆失败的情况下，Demo会尝试自动登录，之前没有重试限制，所以会持续提醒。Demo示例代码如下，可参照修改 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L160
> > 上层应用在实现时要注意自动登录和手工登录的区别，并分别处理。
> 
> 忘记回复了！这个修改就是按照 这个链接里面的修改的！

所以你解决了吗？注意自动登录次数限制（AUTO_LOGIN_TIMES_MAX）了吗？

**Comment by floki2020** [comment]
> > > 你好，如果我没理解错的话，在登陆失败的情况下，Demo会尝试自动登录，之前没有重试限制，所以会持续提醒。Demo示例代码如下，可参照修改 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L160
> > > 上层应用在实现时要注意自动登录和手工登录的区别，并分别处理。
> > 
> > 
> > 忘记回复了！这个修改就是按照 这个链接里面的修改的！
> 
> 所以你解决了吗？注意自动登录次数限制（AUTO_LOGIN_TIMES_MAX）了吗？

这个参考的例子 初始化为3

**Comment by ericliang** [comment]
> > > > 你好，如果我没理解错的话，在登陆失败的情况下，Demo会尝试自动登录，之前没有重试限制，所以会持续提醒。Demo示例代码如下，可参照修改 https://github.com/maxim-top/maxim-uniapp/blob/master/App.vue#L160
> > > > 上层应用在实现时要注意自动登录和手工登录的区别，并分别处理。
> > > 
> > > 
> > > 忘记回复了！这个修改就是按照 这个链接里面的修改的！
> > 
> > 
> > 所以你解决了吗？注意自动登录次数限制（AUTO_LOGIN_TIMES_MAX）了吗？
> 
> 这个参考的例子 初始化为3

嗯，我是提醒一下，看看那个判断的逻辑。你说的在错误密码情况下弹出密码错误和手动输入，是因为不同的事件触发的。如果这些事件你都处理了，可以对应调整一下。

**Comment by ericliang** [comment]
客户超一月无反馈，关闭此问题，如有更新可再次打开。
